1. File Create/Read

In [4]:
f = open("example.txt", "r")
content = f.readlines()

for line in content:
    print(line.strip())

f.close()

Hello World!
Second Line!


2. File Read No. of Characters

In [5]:
f = open("example.txt", "r")

num_chars = int(input("Enter number of characters to read"))
content = f.read(num_chars)

print(content)

f.close()

Hello


3. File Append

In [8]:
f = open("example.txt", "a")

text = input("Enter text to append: ")

f.write(text + "\n")

f.close()

In [ ]:
# to test
f = open("example.txt", "r")
content = f.readlines()

for line in content:
    print(line.strip())

f.close()

Hello World!
Second Line!
Third Line!


4. count_lines_not_starting_with_T

In [11]:
f = open("example.txt", "r")
content = f.readlines()

def count_line_not_starting_with_T(content):
    count = 0
    for line in content:
        if not line.startswith("T"):
            count += 1
    return count

print(count_line_not_starting_with_T(content))

f.close()

2


5. Copy File

In [12]:
f = open("example.txt", "r")
content = f.readlines()

with open("example_copy.txt", "w") as f_copy:
    f_copy.writelines(content)

f.close()

6. NumPy N x M Matrix 

In [39]:
# i
import numpy as np
import random

n = 4
m = 4
matrix = np.zeros((n, m))

for i in range(n):
    for j in range(m):
        matrix[i, j] = random.randrange(1, 100)

print(matrix)

[[33. 92. 98. 82.]
 [83. 58. 92. 43.]
 [ 4.  1. 24. 64.]
 [48. 71. 87. 85.]]


In [40]:
# ii
transpose_matrix = matrix.T
print(transpose_matrix)

[[33. 83.  4. 48.]
 [92. 58.  1. 71.]
 [98. 92. 24. 87.]
 [82. 43. 64. 85.]]


In [41]:
# iii
flattened_matrix = matrix.flatten()
print(flattened_matrix)

[33. 92. 98. 82. 83. 58. 92. 43.  4.  1. 24. 64. 48. 71. 87. 85.]


7. NumPy Array Methods

In [45]:
import numpy as np
arr = np.array([[10, 16, 71, 9], [71, 91, 31, 51]])

# i
print(arr.ndim)

# ii
print(arr.shape)

# iii
print(arr.size)


2
(2, 4)
8


8. NumPy Array Methods 2

In [1]:
import numpy as np
n = 4
m = 4
matrix1 = np.random.randint(100, size=(n, m))
matrix2 = np.random.randint(100, size=(n, m))

In [3]:
# i
matrix_concat = np.concatenate((matrix1, matrix2), axis=1)
print(matrix_concat)

[[52 43 46 62 73 89 97  2]
 [92 97 32 67 69 71 48 13]
 [64 24 55 33 98 83 82 73]
 [53 17 21 89 83 40 70 52]]


In [5]:
# ii
print(np.sort(matrix1))
print(np.sort(matrix2))

[[43 46 52 62]
 [32 67 92 97]
 [24 33 55 64]
 [17 21 53 89]]
[[ 2 73 89 97]
 [13 48 69 71]
 [73 82 83 98]
 [40 52 70 83]]


In [65]:
# iii
matrix_sum = matrix1 + matrix2
print(matrix_sum)

[[ 67 162  54 163]
 [138 138 109 114]
 [ 75 103  57 149]
 [171 153 186 147]]


In [72]:
# iv
matrix_diff = matrix1 - matrix2
print(matrix_diff)

[[ 29   8   8 -17]
 [-58 -24  -1  16]
 [ 65 -53 -25  -9]
 [ 17 -37 -12  35]]


In [70]:
# v
matrix_mult = np.multiply(matrix1, matrix2)
print(matrix_mult)

[[ 912 6545  713 6570]
 [3920 4617 2970 3185]
 [ 350 1950  656 5530]
 [7238 5510 8613 5096]]


In [74]:
# vi
for i in range(0, n):
    for j in range(0, m):
        if matrix2[i, j] == 0:
            matrix2[i, j] = 1
matrix_div = np.divide(matrix1, matrix2)
print(matrix_div)

[[ 2.52631579  1.1038961   1.34782609  0.81111111]
 [ 0.40816327  0.7037037   0.98181818  1.32653061]
 [14.          0.32051282  0.3902439   0.88607595]
 [ 1.22077922  0.61052632  0.87878788  1.625     ]]


9. Numpy Min/Max of Columns

In [91]:
import numpy as np
n = 8
m = 7
matrix = np.random.randint(100, size=(n, m))
print(matrix)

min_cols = np.min(matrix, axis=0)
print(min_cols)
max_cols = np.max(matrix, axis=0)
print(max_cols)

[[82  4 15 81 12 44 21]
 [12  4 41  4 81 39 33]
 [92 75 90 80 16 19 93]
 [27 86 97 11 94 55 14]
 [44 87 29 41 78 14  7]
 [ 1 33  8 82 11 10 30]
 [76 10 93 71 82 88 23]
 [34  0 65 42 51 71 13]]
[ 1  0  8  4 11 10  7]
[92 87 97 82 94 88 93]


10. Numpy + File IO

In [105]:
# i
import numpy as np
n = 4
m = 5
matrix = 1 + np.random.randint(20, size=(n, m))
print(matrix)

[[ 5  8  2  3 13]
 [ 5 14 13 17 18]
 [19  8  3  8 16]
 [ 3  1  4  5 18]]


In [107]:
# ii
matrix_zeros = np.zeros(10)
print(matrix_zeros)

matrix_ones = np.ones(10)
print(matrix_ones)

matrix_fives = 5 + np.zeros(10)
print(matrix_fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [109]:
# iii
matrix_even = np.arange(10, 51, 2)
print(matrix_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [111]:
# iv
n = np.random.random(1)[0]
print(n)

0.7410393925427059


In [113]:
# v
np.savetxt("matrix.txt", matrix, fmt='%d')

loaded_matrix = np.loadtxt("matrix.txt")
print(loaded_matrix)

[[ 5.  8.  2.  3. 13.]
 [ 5. 14. 13. 17. 18.]
 [19.  8.  3.  8. 16.]
 [ 3.  1.  4.  5. 18.]]
